// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezwebsocket.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezwebsocket.WebsocketManager;

/**
 * Use this if you need custom timeout settings
 * - Session timeout can be set to 0 for infinite* sessions
 * *NOTE: Mendix cloud will still disconnect after 60 seconds of inactivity
 * 
 * Set pingTime and pongTime if you want to control the keepalive mechanism
 * - The server will ping the client every <pingTime> seconds
 * - The server will disconnect the client after not receiving a response after <pongTime> seconds
 * > Setting pingTime to 0 (or negative) will turn off the keepalive mechanism and clients will timeout after <sessionTimeout> seconds
 */
public class JA_AddWebsocketEndpoint_Advanced extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String websocketIdentifier;
	private java.lang.Long sessionTimeout;
	private java.lang.Long pingTime;
	private java.lang.Long pongTime;

	public JA_AddWebsocketEndpoint_Advanced(IContext context, java.lang.String websocketIdentifier, java.lang.Long sessionTimeout, java.lang.Long pingTime, java.lang.Long pongTime)
	{
		super(context);
		this.websocketIdentifier = websocketIdentifier;
		this.sessionTimeout = sessionTimeout;
		this.pingTime = pingTime;
		this.pongTime = pongTime;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return WebsocketManager.addWebsocketEndpoint(websocketIdentifier, sessionTimeout, pingTime, pongTime != null ? pongTime : 0);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_AddWebsocketEndpoint_Advanced";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
